#ifndef CHECKHEADER_SLIB_AUDIO_DEFINITION
#define CHECKHEADER_SLIB_AUDIO_DEFINITION

#include "../core/definition.h"

#define SLIB_AUDIO_NAMESPACE_BEGIN	SLIB_NAMESPACE_BEGIN
#define SLIB_AUDIO_NAMESPACE_END	SLIB_NAMESPACE_END

#endif
