#ifndef CHECKHEADER_SLIB_MAP_DEFINITION
#define CHECKHEADER_SLIB_MAP_DEFINITION

#include "../core/definition.h"

#define SLIB_MAP_NAMESPACE_BEGIN	SLIB_NAMESPACE_BEGIN
#define SLIB_MAP_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
