#ifndef CHECKHEADER_SLIB_MATH_DEFINITION
#define CHECKHEADER_SLIB_MATH_DEFINITION

#include "../core/definition.h"

#define SLIB_MATH_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_MATH_NAMESPACE_END			SLIB_NAMESPACE_END

#endif
