#ifndef CHECKHEADER_SLIB_P2P_DEFINITION
#define CHECKHEADER_SLIB_P2P_DEFINITION

#include "../core/definition.h"

#define SLIB_P2P_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN namespace p2p{
#define SLIB_P2P_NAMESPACE_END			} SLIB_NAMESPACE_END

#define SLIB_P2P_PACKET_MAX_SIZE 5000
#define SLIB_P2P_CERTIFICATE_MAX_SIZE 4096
#define SLIB_P2P_RSA_KEY_MIN_SIZE 128
#define SLIB_P2P_RSA_KEY_MAX_SIZE 512
#define SLIB_P2P_HOSTID_MAX_SIZE 64
#define SLIB_P2P_ADDRESS_MAX_SIZE 64

#endif
