#ifndef CHECKHEADER_SLIB_MOBILE_DEFINITION
#define CHECKHEADER_SLIB_MOBILE_DEFINITION

#include "../core/definition.h"

#define SLIB_DEVICE_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_DEVICE_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
