#ifndef CHECKHEADER_SLIB_DATABASE_DEFINITION
#define CHECKHEADER_SLIB_DATABASE_DEFINITION

#include "../core/definition.h"

#define SLIB_DATABASE_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_DATABASE_NAMESPACE_END			SLIB_NAMESPACE_END

#endif
