#ifndef CHECKHEADER_SLIB_DB_DEFINITION
#define CHECKHEADER_SLIB_DB_DEFINITION

#include "../core/definition.h"

#define SLIB_DB_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_DB_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
