#ifndef CHECKHEADER_SLIB_MEDIA_DEFINITION
#define CHECKHEADER_SLIB_MEDIA_DEFINITION

#include "../core/definition.h"

#define SLIB_MEDIA_NAMESPACE_BEGIN	SLIB_NAMESPACE_BEGIN
#define SLIB_MEDIA_NAMESPACE_END	SLIB_NAMESPACE_END

#endif
