#ifndef CHECKHEADER_SLIB_CRYPTO_DEFINITION
#define CHECKHEADER_SLIB_CRYPTO_DEFINITION

#include "../core/definition.h"

#define SLIB_CRYPTO_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_CRYPTO_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
