#ifndef CHECKHEADER_SLIB_CODEC_DEFINITION
#define CHECKHEADER_SLIB_CODEC_DEFINITION

#include "../core/definition.h"
#define SLIB_CODEC_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_CODEC_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
