#ifndef CHECKHEADER_SLIB_STREAMER_DEFINITION
#define CHECKHEADER_SLIB_STREAMER_DEFINITION

#include "../core/definition.h"

#define SLIB_STREAMER_NAMESPACE_BEGIN	SLIB_NAMESPACE_BEGIN namespace streamer {
#define SLIB_STREAMER_NAMESPACE_END		} SLIB_NAMESPACE_END

#endif
