#ifndef CHECKHEADER_SLIB_CAPTURE_DEFINITION
#define CHECKHEADER_SLIB_CAPTURE_DEFINITION

#include "../core/definition.h"

#define SLIB_CAPTURE_NAMESPACE_BEGIN	SLIB_NAMESPACE_BEGIN
#define SLIB_CAPTURE_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
