#ifndef CHECKHEADER_SLIB_WEB_DEFINITION
#define CHECKHEADER_SLIB_WEB_DEFINITION

#include "../core/definition.h"

#define SLIB_WEB_NAMESPACE_BEGIN	SLIB_NAMESPACE_BEGIN
#define SLIB_WEB_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
