#ifndef CHECKHEADER_SLIB_UI_DEFINITION
#define CHECKHEADER_SLIB_UI_DEFINITION

#include "../core/definition.h"

#define SLIB_UI_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_UI_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
